<?php

namespace AppBundle\Repository;

use AppBundle\Document\Project;
use AppBundle\Document\Task;
use AppBundle\Document\User;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends DocumentRepository
{
    /**
     * @param Project $project
     * @return null|Task
     */
    public function findAllByProject(Project $project)
    {
        return $this->createQueryBuilder()
            ->field('project')->references($project)
            ->sort('created', -1)
            ->getQuery()
            ->execute();
    }

    /**
     * @param User $user
     * @return Task|null
     */
    public function findAllByUser(User $user)
    {
        return $this->createQueryBuilder()
            ->field('performer')->references($user)
            ->sort('created', -1)
            ->getQuery()
            ->execute();
    }
}
